### ISSUE TITLE
Object.entries is not a function

### ISSUE THREAD

**Issue by maiermic** [erykpiast/autocompleted-select#1]
I just did
```
git clone https://github.com/erykpiast/autocompleted-select.git
cd autocompleted-select
npm install
gulp
```
Opened demo (http://localhost:8080), saw a blank side, looked in the console:
```
Uncaught TypeError: Object.entries is not a function    create-streams-group.js:70
```

**Comment by erykpiast** [comment]
Hey, thank you for bug report! It was a bug indeed, but in [cyclejs-group](https://github.com/erykpiast/cyclejs-group), missing ES6 polyfill. Fixed with [v0.1.0](https://github.com/erykpiast/autocompleted-select/releases/tag/v0.1.0)
