### ISSUE TITLE
extract create-component.js

### ISSUE THREAD

**Issue by vic** [erykpiast/autocompleted-select#2]
Just like your `cyclejs-mock`, I believe extracting the tiny code inside your `create-component.js` would be nice for having more people create and share more components using Rx.

**Comment by erykpiast** [comment]
That is true! I've just been waiting what will happen with Cycle components, but now we have drivers and it seems components and WCs don't collide with each other... You motivated me to go back to the topic :) So, I've created [separated repository](https://github.com/erykpiast/cyclejs-wc), we can move this discussion there!

**Comment by vic** [comment]
Hey, thanks a lot !
